#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <example-name>"
  echo "Example: $0 outlet"
  exit 1
fi

NAME="$1"
TARGET_DIR="examples/$NAME"

if [[ -e "$TARGET_DIR" ]]; then
  echo "[error] Example already exists: $TARGET_DIR"
  exit 2
fi

mkdir -p "$TARGET_DIR/main"

cat > "$TARGET_DIR/CMakeLists.txt" <<'CMAKE'
cmake_minimum_required(VERSION 3.16)

set(EXTRA_COMPONENT_DIRS "${CMAKE_CURRENT_LIST_DIR}/../../components")

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(example_project)
CMAKE

cat > "$TARGET_DIR/main/CMakeLists.txt" <<'CMAKE'
idf_component_register(SRCS "main.cpp"
                       INCLUDE_DIRS "."
                       REQUIRES esp32_matter_thread nvs_flash)
CMAKE

cat > "$TARGET_DIR/main/idf_component.yml" <<'YAML'
dependencies:
  espressif/esp_matter: "*"
YAML

cat > "$TARGET_DIR/main/main.cpp" <<'CPP'
#include <esp_log.h>

extern "C" void app_main(void) {
    ESP_LOGI("example", "Scaffold generated. Implement your accessory here.");
}
CPP

cat > "$TARGET_DIR/README.md" <<'MD'
# Example scaffold

Generated by `./scripts/new_example.sh`.
Implement Matter endpoint creation and callbacks in `main/main.cpp`.
MD

echo "[ok] Created scaffold: $TARGET_DIR"
